# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Firebase Deploy
          command: npm run deploy -- --token=$FIREBASE_TOKEN
workflows:
  version: 2
  nightly: 
    triggers: 
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - none
    jobs:
      - build:
          filters:
            branches:
              only:
              - none

  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
              - master